### ISSUE TITLE
Former Skotos Links and Map Arrows Broken

### ISSUE THREAD

**Issue by kurzon-marrach** [ChatTheatre/orchil#16]
Hi all,

Since the shutdown of skotos.net, images referenced by the Orchil client no longer load. This includes things like the "Getting Started" and "Mastering Chat" buttons on the right side panel, but more importantly, the navigation arrows that normally encircle the bottom-right map fragment, which are highlighted blue to indicate the cardinal directions someone can travel from their current environment. The latter are particularly important as the map images in some rooms are not explicitly clear which direction someone can travel in without those arrows.

**Comment by ChristopherA** [comment]
The orchil client should use the images from base url defined in Theatre object, so that every game can change them. They can be served from anywhere — I prefer for small games to use a static github repo with web pages turned on.

@saraht45 can you help us document the minimum number of images that Orchil and the default pages need? We should create a generic repo with them as the default for new theaters..

**Comment by noahgibbs** [comment]
With the new PR to remove NGinX, we should serve those images from DGD, at least in dev mode. I have the asset repo from prod Gables added in that PR, but I don't think that includes all skotos.net images. I definitely see a few skotos.net URLs in some of the XML objects that I haven't yet updated.

**Comment by kurzon-marrach** [comment]
> The orchil client should use the images from base url defined in Theatre object, so that every game can change them. They can be served from anywhere — I prefer for small games to use a static github repo with web pages turned on.

To clarify, this is an object we can pull up in Woe and edit the properties therein to redirect where Orchil pulls its images from? The closest object I can find with a +woe search is _SID:Theatre:Theatre_ but I don't think this is it.

**Comment by shentino** [comment]
Definitely not, anything under SID is basically a format for how data is
passed between xml and the object's internal state.  It defines all the
fields and elements of the xml as edited in WOE.

**Comment by anony-0** [comment]
I should preface this by first saying I have no clue how this really works... still stumbling along... but...

I assumed this property "realmurl='<yourartworkdirectory' which is found in the theatres folder (at least for me) sort of handled the location for where the clients grabbed artwork. It's in that object where we define home, jail and so on.

However I also have the missing arrows issue, and to make things even worse, I'm also missing the left/right side art. So.... maybe that needs to be fixed somewhere else, at least for me. I'm still waiting to hear back from Shannon on how this all works, and am also somewhat limited as I don't have the linode yet and redirects from multiverse are sort of breaking a couple of things for me.

I also have a problem with bigmaps not working, but I think that is a redirect issue.

Anyway, just figured I'd mention the realmurl thing... as I assumed that is what should redirect the artwork to the right place. One odd thing I noticed is how in CM zealoty is sort of completely bonkers as far as side panel art and arrows... while strangely for me in zealotry it seems to work fine and can find the maps/side panels/arrows.  Maybe for CM, Zealotry used a slightly different directory or naming structure when the images were hosted at skotos vs wherever they are now?

**Comment by ChristopherA** [comment]
@saraht45 Do you have some clues that can help us in general for a base line of images, and best practices for new games for additional images?

**Comment by kurzon-marrach** [comment]
> I assumed this property "realmurl='<yourartworkdirectory' which is found in the theatres folder (at least for me) sort of handled the location for where the clients grabbed artwork. It's in that object where we define home, jail and so on.

In Castle Marrach's case, the issue we're facing is that folder doesn't exist.

Some years ago, when Castle Marrach made the switch to Freemium, I had wanted to redo our character login gateway to facilitate our Freemium in a manner similar to Ironclaw; between Geist and myself, and Azrael (who set up that same system for Ironclaw) we simply couldn't get it to work that way in Castle Marrach. We could only determine that, being Skotos' first game, the forethought wasn't yet there to set up the Castle Marrach theatre in the same manner as the rest of the Skotos games that followed it. Many of the Woe folders that exist in other former Skotos theaters that allow admin staff to manipulate things like the Character Gateway, the CharGen process or the Theatre folder, simply don't exist.

In any case, a bit of a tangent.

A quick look at the broken arrow hyperlink shows that the map arrows the client is trying to display were located at http://www.skotos.net/CastleMarrachGame/images/arrows/se-noex.gif. I assume "se-noex" is "southeast no exit", so the greyed out SE arrow. Curious that it was saved as a gif. Anyway, I tried to pull up http://images.marrach.com/arrows/se-noex.gif which is where that file **_should_** now be after the server copy -- but to no avail, I get a 403 Forbidden when I try to bring it up in my browser.

**Comment by anony-0** [comment]
Hmm... yeah, that may be a problem if you don't have that theatre object, although then I wonder how the client knows where to pull the images from? That data has to be stored somewhere. Maybe in some underlying code you don't have easy access to (at least via woe)?

I just checked here in Lazarus and our little arrows are stored the same way, as gifs (no idea why). Non-working for orchil, but working for zealotry.

I was about to suggest copying over a set of arrows to your images.marrach.com folder, which at least might fix the zealotry issue, but since the hyperlink is looking for the arrows at skotos.net, I don't see how that would help. It seems like you need to both correct the link and make sure the arrows are in the new images folder.

**Comment by noahgibbs** [comment]
@kurzon-marrach - looking in orchil/marrach/marrach.js, I'm seeing some hardcoded Skotos.net URLs. Here are three I found with a quick search on the string "skotos.net":

~~~
marrach.js
5:		addComponent('chat_theatre'   , 'left'    , false, 'openerWin', ['http://marrach.skotos.net/'], '<img alt="Grand Theatre" src="http://images.marrach.com/gamelogo.gif">');
10:		addComponent('newplayers'     , 'right'   , false, 'openerWin', ['http://game.marrach.com/Marrach/starting.sam'], '<img alt="Getting Started" src="http://www.skotos.net/CastleMarrachGame/images/started.gif">');
11:		addComponent('newplayers'     , 'right'   , false, 'openerWin', ['http://game.marrach.com/Marrach/mastering.sam'], '<img alt="Mastering Chat" src="http://www.skotos.net/CastleMarrachGame/images/mastering.gif">');
353:		artwin = window.open('http://marrach.skotos.net/Theatre/Art.sam?url=' +
~~~

If you change those URLs to point somewhere else, that should fix at least some of the problem, including the "Mastering Chat" and "Getting Started" buttons.

I'm seeing a few other skotos.net references, mostly in help text and older games. Not clear if that needs to be fixed or not.

**Comment by anony-0** [comment]
Want to give thanks to Noah, as based on his comments on marrach, I found the culprit for my own arrow woes in my lazarus.js. It's a lot easier now that that I have access, at least I can try to hunt down these files..

Fixed my arrows last night, but being an idiot I didn't realize I needed to clear my cache to see them. I still have some other links to fix, like the chat and getting started stuff, but at least the arrows are there... and now I want to clean them up as they are kind of bulky and blocky...

Anyway, as far as Marrach, can't you just get a set of arrows and put them in your image folder (I guess first make sure they aren't hidden in some oddball folder already), then make sure your js file is pointing in the right direction? It'd also be a chance to make nicer arrows if you want.

Don't think that would help w/ zealotry, but should help with the missing orchil arrows.

**Comment by kurzon-marrach** [comment]
I'll take a look hopefully tomorrowish and see what I see. If it's as simple as dropping some image files in a folder then great. We have a big month-long Xmas themed event starting later today in Marrach and prep for that has taken up my free time lately. We don't really have any shell experience on our Staff over here so it'll require a bit of fiddling and learning, but that's a separate matter.

I'll let you know how it goes. :)

**Comment by anony-0** [comment]
Based on the code here in your js file (assuming it's the same in CM) it looks like the arrows just need to be put in:

http://images.marrach.com/images/arrows/" + dir + "-ex.gif)";
http://images.marrach.com/arrows/" + dir + "-noex.gif)";

Which strangely are separated into an extra subdirectory for the -noex.gif arrows. 

 New to this myself, but I'd expect if you use winscp (or whatever ftp client you prefer) to move the arrows to where they need to be, it should work? I think? 

Kind of odd your arrows are misplaced though. Maybe they are just in a different directory somewhere, in which case you could just edit your js file instead.

**Comment by kurzon-marrach** [comment]
We closed this by uploading the map arrows to the image directory, and patching the orchil files to direct to images.marrach.com instead of skotos.net.

**Comment by noahgibbs** [comment]
Sounds perfect. In the most recent SkotOS revisions I'm actually moving the Orchil files into a DGD-visible directory so that they can more easily be packaged together with the other game-specific files. I think that's a better place for them.

In any case, sounds like a good fix!
