### ISSUE TITLE
Text entry field is not themed

### ISSUE THREAD

**Issue by AnthonyHJ** [ChatTheatre/orchil#26]
Orchil doesn't retheme the command entry box (id: "commandinput")
![image](https://user-images.githubusercontent.com/10799143/109995916-a1a2aa00-7d06-11eb-87bf-b5d8e57de5e1.png)

More a suggestion than an issue, but players have been asking for recolouring that element to match the selected theme.
![image](https://user-images.githubusercontent.com/10799143/109996221-ed555380-7d06-11eb-9237-df69f5b3bacc.png)

**Comment by noahgibbs** [comment]
Okay. I've added a commit to the PR that should fix this too.
