### ISSUE TITLE
Orchil seems to strip characters with diacritics instead of just the diacritic.

### ISSUE THREAD

**Issue by AnthonyHJ** [ChatTheatre/orchil#28]
A Castle Marrach player was complaining about 'Françoise' being rendered as 'Franoise' - I know the words go to and from the server correctly, but Orchil doesn't render them.  

Performing **string.normalize("NFD")** splits these characters into a standard letter and the accent. Additionally, **string.normalize("NFD").replace(/[\u0300-\u036f]/g, "");** will strip the accents and leave only the letters. Françoise becomes Francoise.

**Comment by ChristopherA** [comment]
@saraht45 Can you take a look and see if you can address this bug?

**Comment by saraht45** [comment]
PR #29 should take care of this. Thanks, Anthony!
